"""Add email verification fields

Revision ID: 0d2e3905db58
Revises: be87d11f7ecd
Create Date: 2026-01-13 09:43:16.492920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d2e3905db58'
down_revision = 'be87d11f7ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verificata', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('token_verifica', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['token_verifica'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('token_verifica')
        batch_op.drop_column('email_verificata')

    # ### end Alembic commands ###
