"""Add override_partecipanti field to events

Revision ID: 2fee59b3f350
Revises: 0d2e3905db58
Create Date: 2026-01-14 15:38:03.498098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2fee59b3f350'
down_revision = '0d2e3905db58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('override_partecipanti', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('ruolo',
               existing_type=mysql.ENUM('sidekick', 'tablhero', 'veteran', 'game_architect', 'founder'),
               nullable=False,
               existing_server_default=sa.text("'sidekick'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('ruolo',
               existing_type=mysql.ENUM('sidekick', 'tablhero', 'veteran', 'game_architect', 'founder'),
               nullable=True,
               existing_server_default=sa.text("'sidekick'"))

    with op.batch_alter_table('eventi', schema=None) as batch_op:
        batch_op.drop_column('override_partecipanti')

    # ### end Alembic commands ###
