"""add prezzo evento

Revision ID: be87d11f7ecd
Revises: 
Create Date: 2026-01-12 21:46:36.764877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be87d11f7ecd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_logs')
    with op.batch_alter_table('eventi', schema=None) as batch_op:
        batch_op.alter_column('prezzo',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))

    with op.batch_alter_table('partecipazioni', schema=None) as batch_op:
        batch_op.alter_column('data_partecipazione',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_constraint(batch_op.f('partecipazioni_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('partecipazioni_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'eventi', ['evento_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('ha_pagato_evento')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('stripe_customer_id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('data_registrazione',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('data_registrazione',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('stripe_customer_id',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('partecipazioni', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ha_pagato_evento', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('partecipazioni_ibfk_2'), 'eventi', ['evento_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('partecipazioni_ibfk_1'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('data_partecipazione',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('eventi', schema=None) as batch_op:
        batch_op.alter_column('prezzo',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))

    op.create_table('admin_logs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('admin_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('azione', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('target_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name=op.f('admin_logs_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
